<?php

// autoload_namespaces.php @generated by Composer

$libraryDir = dirname(dirname(dirname(__FILE__))).'/library';

return [
	'Library' => [$libraryDir.'/icracked/lib']
];
//
//return array(
//    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
//    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
//    'Symfony\\Component\\Templating\\' => array($vendorDir . '/symfony/templating'),
//    'Symfony\\Component\\Stopwatch\\' => array($vendorDir . '/symfony/stopwatch'),
//    'Symfony\\Component\\Routing\\' => array($vendorDir . '/symfony/routing'),
//    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
//    'Symfony\\Component\\HttpKernel\\' => array($vendorDir . '/symfony/http-kernel'),
//    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
//    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
//    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
//    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
//    'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/dom-crawler'),
//    'Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
//    'Symfony\\Component\\Debug\\' => array($vendorDir . '/symfony/debug'),
//    'Symfony\\Component\\CssSelector\\' => array($vendorDir . '/symfony/css-selector'),
//    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
//    'Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
//    'Symfony\\Component\\BrowserKit\\' => array($vendorDir . '/symfony/browser-kit'),
//    'Symfony\\Bundle\\FrameworkBundle\\' => array($vendorDir . '/symfony/framework-bundle'),
//    'Symfony\\Bridge\\Doctrine\\' => array($vendorDir . '/symfony/doctrine-bridge'),
//    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
//    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
//    'Incenteev\\ParameterHandler' => array($vendorDir . '/incenteev/composer-parameter-handler'),
//    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
//    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
//    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
//    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
//    'Goutte' => array($vendorDir . '/fabpot/goutte'),
//    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
//    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
//    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
//    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
//    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
//    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
//    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
//    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
//    'Doctrine\\Bundle\\DoctrineBundle' => array($vendorDir . '/doctrine/doctrine-bundle'),
//    '' => array($baseDir . '/src'),
//);
